services:
  app:
    build: .
    volumes:
      - ./:/root/take_home_project
    command: ["run_ark_app"]
    ports:
      - "8000:8000"
    env_file:
      - ./local.env
  db:
    image: postgres:15.2
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - ./local.env
